### ISSUE TITLE
peneira aborts

### ISSUE THREAD

**Issue by MrUnknown789556** [anapaulagomes/peneira#29]
I have errors when I try to run the module.

C:\Users\niels>peneira -s open_alex -o bibtex -f my-papers.bib
Please enter the search string for open_alex: 'ceramic spheres' uhpc
open_alex: Fetching articles for OPEN_ALEX... 24 papers distributed in 1 pages.
Executing the search...

I here attach the logging of the error messages.

[Traceback (most recent call last).txt](https://github.com/user-attachments/files/16381904/Traceback.most.recent.call.last.txt)

/Frank

**Comment by anapaulagomes** [comment]
Hi @MrUnknown789556! I ran it here and it worked fine (file attached). Could you please share your OS and Python versions? Maybe adding the encoding (`encoding="utf-8"`) while [writing the file](https://github.com/anapaulagomes/peneira/blob/73548c7148df3506c5437f6ae6344282479c32c7/peneira/exporters.py#L34) would help here...

[my-papers.bib.zip](https://github.com/user-attachments/files/16390753/my-papers.bib.zip)

**Comment by MrUnknown789556** [comment]
Thank very much for quick repsponse.
I use Python 3.12.4.
About Windows version, I use Windows 11, version 23H2 (build 22631.3958).
I'm without knowledge of the Python language. I don't know about how to set (and where) encoding to utf-8.
I just want to use you very nice script peneira in CLI mode. I hope that will be possible.

##########################################################
I asked an AI agent what to do:
Can I set encoding to utf-8 in the prompt screen, just before I run the peneira CLI command? How?
Answer:
No, you cannot set the encoding to UTF-8 directly in the command prompt or terminal before running the peneira CLI command. The encoding is typically specified within the Python script itself when opening or writing files.
To set the encoding when writing a file in Python, you can pass the encoding parameter to the open() function, like this:
```pythonwith open("file.txt", "w", encoding="utf-8") as file:    file.write("Some text")```
In the context of the peneira script, you would need to locate the part of the code where files are being written and ensure that the encoding is set to "utf-8" there.
If you don't have access to modify the peneira source code directly, you can reach out to the project maintainer or open an issue on the project's repository, suggesting the addition of the encoding parameter to resolve potential encoding-related issues across different systems.
Remember to provide your operating system and Python version details when reporting the issue, as requested by the developer, to help them better understand and reproduce the problem.
Citations:[1] https://ppl-ai-file-upload.s3.amazonaws.com/web/direct-files/3487700/e3c216ff-7837-4fc0-9e8f-442324f6c5d6/Issue-29.pdf

    Den fredag den 26. juli 2024 kl. 13.10.28 CEST skrev Ana Paula Gomes ***@***.***>:  
 
 


Hi @MrUnknown789556! I ran it here and it worked fine (file attached). Could you please share your OS and Python versions? Maybe adding the encoding (encoding="utf-8") while writing the file would help here...

my-papers.bib.zip

**Comment by anapaulagomes** [comment]
@MrUnknown789556 I've tested a fix locally and it is simple to fix but I want to add tests for windows, so we can catch errors before it gets to people. I'll work on it in the next days. I'll keep this issue updated!

**Comment by MrUnknown789556** [comment]
Hi Ana.

You have forgotten to put the updated version into the Python Package Index (PyPI) repository.

The latest version you have there at the moment is version 0.2.0 (Jul 2, 2024).

/Frank

**Comment by anapaulagomes** [comment]
Dear Frank, I didn’t forget. I had to do other things before publishing a new version. :) It is out now. Please let me know if it works.

**Comment by MrUnknown789556** [comment]
I works just perfect.
I tried with different search items, where there were a few hits, and also with many hits. 
It was a pleasure to use it.
/Frank


    Den onsdag den 4. september 2024 kl. 15.30.47 CEST skrev Ana Paula Gomes ***@***.***>:  
 
 


Dear Frank, I didn’t forget. I had to do other things before publishing a new version. :) It is out now. Please let me know if it works.
